name: Check for TEI

on:
  workflow_dispatch

jobs:
  download:
    name: Find TEI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt
    - name: Find TEI
      run: |
        python maninfestations_have_tei.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Available TEI to CSV