name: Validate xml

on:
  workflow_dispatch

jobs:
  validate:
    name: Validate xml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |        
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install --upgrade pip
        sudo apt-get install libxml2-dev libxslt-dev python-dev zlib1g-dev
        pip install -r requirements.txt
        python validate_xml.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: XML validation logs created
