name: Validate xml

on:
  workflow_dispatch

jobs:
  validate:
    name: Validate xml
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{secrets.BASEROW_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        python validate_xml.py

